johncms/johncms

- library/inc.php
- library/includes/addnew.php
- library/includes/comments.php
- library/includes/del.php
- library/includes/download.php
- library/includes/lastcom.php
- library/includes/mkdir.php
- library/includes/moder.php
- library/includes/new.php
- library/includes/premod.php
- library/includes/search.php
- library/includes/tagcloud.php
- library/includes/tags.php
- library/includes/top.php
- library/index.php
- library/locale/en/default.pot
> Файлы /library/* переведены на Gettext

- incfiles/classes/bbcode.php
BB коды не работали в цитате, если в админке поставит адрес сайта на относительный.
> BB коды не работали в цитате

- panel/includes/usr_clean.php
> Fix SQL запрос

- .htaccess
> Страницы ошибок

- incfiles/classes/counters.php
Порт доработки от JohnCMS 7 для JohnCMS 6
> Добавлено 10 секундное кэширование счетчика Онлайн

- incfiles/head.php
> Исправил head.php

- panel/includes/access.php
- panel/includes/ads.php
- panel/includes/antiflood.php
- panel/includes/antispy.php
- panel/includes/counters.php
- panel/includes/forum.php
- panel/includes/ipban.php
- panel/includes/karma.php
- panel/includes/languages.php
- panel/includes/mail.php
- panel/includes/news.php
- panel/includes/reg.php
- panel/includes/settings.php
- panel/includes/sitemap.php
- panel/includes/usr_clean.php
- panel/includes/usr_del.php
- users/includes/profile/edit.php
- users/includes/profile/reset.php
Fix redirect URL in Admin panel
Delete unused code
> Fix some things

- incfiles/classes/bbcode.php
> Fixed parsing of the tag within the code

- forum/includes/new.php
Еще оптимизация в непрочитанных/новых.
Надо бы на большой таблице проверить, и форсировать индекс в запросе блока default force index for join(forum_topic_section_id)
> Оптимизация запросов в последних темах

- forum/includes/new.php
- forum/index.php
> Лишние Запросы в циклах

- config/routes.php
- modules/guestbook/index.php
- modules/guestbook/templates/clear.phtml
- modules/guestbook/templates/confirm_delete.phtml
- modules/guestbook/templates/edit.phtml
- modules/guestbook/templates/index.phtml
- modules/guestbook/templates/reply.phtml
- modules/news/includes/add.php
- modules/news/includes/clean.php
- modules/news/includes/del.php
- modules/news/includes/edit.php
- modules/news/index.php
- modules/news/templates/add.phtml
- modules/news/templates/clear.phtml
- modules/news/templates/confirm_delete.phtml
- modules/news/templates/edit.phtml
- modules/news/templates/index.phtml
- Translate comments
- Friendly URL for guestbook
> Some change

- modules/forum/includes/addfile.php
- modules/forum/index.php
Несовместимость с php7.4.
Неверно определался тип файла при записи в DB.
> Доработки форума

- modules/downloads/includes/top_users.php
> Optimize SQL query

- modules/forum/includes/new.php
- modules/forum/index.php
> Non-numeric value fixed & code optimized

- modules/forum/includes/deltema.php
> Удаление темы; Удалялись не все связи таблиц

- modules/forum/includes/curators.php
> Fix incompatible with sql_mode

- modules/profile/includes/settings.php
> Fix empty data

- modules/forum/includes/files.php
- modules/forum/templates/files_list.phtml
- modules/forum/templates/files_sections.phtml
> Optimization query & easy refactoring

- modules/forum/includes/say.php
Ссылка на профиль цитируемого юзера
> Quote profile link

- modules/library/includes/lastcom.php
> Fix last comment output

- modules/profile/skl.php
Там еще $_POST надо прибрать как то.
> Password recovery fixed

- modules/album/includes/edit.php
- modules/album/includes/index.php
- modules/album/includes/top.php
- modules/album/includes/users.php
Убрал GROUP BY clause and contains nonaggregated column,
Фотки видно по прямой ссылке, от паролей по большому счету толку мало))
> Fixed access to hidden photos(subjective)

- modules/album/includes/top.php
> Reverts to file albums top.php

- modules/forum/includes/who.php
Лучше чем добавить запрос в цикл, ничего не придумал:)
> Fixed location on the forum

- modules/downloads/includes/scan_dir.php
> Cyrillic replacement in files

- modules/downloads/includes/scan_dir.php
Добавил - удаление пустых папок, и оригинальное имя для отображения.
> Cyrillic replacement in files uploads

- modules/profile/includes/index.php
// TODO: Счетчик фотографий зачем?
> Redundant & incorrect grouping

- modules/admin/includes/search_ip.php
> Fix SQL nonaggregated column
